select Distinct  
       PATIENT.PAT_MRN_ID 
      ,pat_enc.PAT_ENC_CSN_ID
	   ,pat_enc.CONTACT_DATE
       ,arpb.CPT_CODE
	   ,IP_FLO_GP_DATA.FLO_MEAS_ID
	   ,IP_FLO_GP_DATA.FLO_MEAS_NAME	
	   ,IP_FLWSHT_MEAS.TAKEN_USER_ID
	   ,CLARITY_SER.PROV_NAME
	   ,CLARITY_EMP.NAME
	   ,CLARITY_SER.PROVIDER_TYPE_C
	    ,ZC_PROV_TYPE.NAME 
	   ,IP_FLWSHT_MEAS.RECORDED_TIME	
	   ,IP_FLO_GP_DATA.DISP_NAME as FlowsheetQuestion
	   ,IP_FLO_GP_DATA.FLO_MEAS_NAME as FlowsheetMeasureName
	    ,IP_FLWSHT_MEAS.MEAS_VALUE as 'Value_recorded_in_Mintues'
from CLARITY.dbo.PAT_ENC 
join CLARITY.dbo.ARPB_TRANSACTIONS arpb
   on pat_enc.PAT_ENC_CSN_ID=arpb.PAT_ENC_CSN_ID
INNER JOIN CLARITY.dbo.PATIENT on PAT_ENC.PAT_ID = PATIENT.PAT_ID
INNER JOIN clarity.dbo.IP_FLWSHT_REC on IP_FLWSHT_REC.INPATIENT_DATA_ID = PAT_ENC.INPATIENT_DATA_ID
inner join clarity.dbo.IP_FLWSHT_MEAS on IP_FLWSHT_MEAS.FSD_ID = IP_FLWSHT_REC.FSD_ID
inner join clarity.dbo.IP_FLO_GP_DATA on IP_FLO_GP_DATA.FLO_MEAS_ID = IP_FLWSHT_MEAS.FLO_MEAS_ID
LEFT OUTER JOIN clarity.dbo.ALL_CATEGORIES on IP_FLO_GP_DATA.CAT_INI = ALL_CATEGORIES.INI and IP_FLO_GP_DATA.CAT_ITEM = ALL_CATEGORIES.ITEM   --and IP_FLWSHT_MEAS.MEAS_VALUE = ALL_CATEGORIES.VALUE_C
LEFT OUTER JOIN clarity.dbo.IP_FLT_DATA  on IP_FLO_GP_DATA.FLO_MEAS_ID = IP_FLT_DATA.TEMPLATE_ID
LEFT OUTER JOIN clarity.dbo.CLARITY_EMP on CLARITY_EMP.USER_ID = IP_FLWSHT_MEAS.TAKEN_USER_ID
LEFT OUTER JOIN clarity.dbo.CLARITY_SER on CLARITY_SER.USER_ID=	CLARITY_EMP.USER_ID
LEFT OUTER JOIN clarity.dbo.ZC_PROV_TYPE on ZC_PROV_TYPE.PROV_TYPE_C =	CLARITY_SER.PROVIDER_TYPE_C -- NOT ZC_PROVIDER_TYPE 
WHERE IP_FLWSHT_REC.RECORD_DATE> = '2021-08-01'
--DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())-12,0)
    and IP_FLO_GP_DATA.FLO_MEAS_NAME like '%dsmes%'
	and IP_FLO_GP_DATA .FLO_MEAS_ID ='7451'
	and CLARITY_EMP.USER_ID='1956'
	and arpb.CPT_CODE in ('99211','G0108')
	--and PATIENT.PAT_MRN_ID  in('000000020827','000010107198')
	order by PAT_ENC.CONTACT_DATE